### ISSUE TITLE
please update README.jmd and weave it using Weave.jl

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaString/ShortStrings.jl#37]
instead of updating README.md

@oxinabox

**Comment by oxinabox** [comment]
I haven't touched the readme, AFAIK

**Comment by xiaodaigh** [comment]
@ScottPJones

**Comment by ScottPJones** [comment]
I did use Weave - it took me a while to figure it out, because I needed to get RCall, Weave, and a couple other packages added to my environment to run it.
